### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by cfguimaraes** [xfiveco/css-coding-standards#1]
Hi, I was reading your convention and found this, I believe that it is an error.

Do not use unit with 0.
```CSS
/* Correct */
.nav a {
  padding: 5px 0 5px 2px;
}

/* Wrong */
.nav a {
  padding: 5px 0px 5px 2px;
}
```

You say to **not** use unit with 0, but in the example the correct way **uses 0** as measure unit.
